replicaCount: 1

image:
  repository: ghcr.io/jdweeks/draught
  pullPolicy: Always
  tag: main

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  autoIngress: true
  type: ClusterIP
  port: 80

app:
  kafka:
    bootstrap: kafka-0.kafka-headless.kafka-jdweeks.svc.cluster.local:9092
  mongodb:
    uri: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo-mongodb.mongo-jdweeks.svc.cluster.local:27017
  optaplanner:
    limit: 60m

autoscaling:
  enabled: false

resources: {}

env: []

secrets: []