replicaCount: 1

image:
  repository: ghcr.io/jdweeks/draught
  pullPolicy: Always
  tag: main

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  auto-ingress: true
  type: ClusterIP
  port: 80

autoscaling:
  enabled: false

resources: {}