apiVersion: v1
kind: ConfigMap
metadata:
  name: draught-config
data:
  application.properties: |-
    quarkus.optaplanner.solver.termination.spent-limit={{ .Values.app.optaplanner.limit }}
    quarkus.mongodb.connection-string={{ .Values.app.mongodb.uri }}
    kafka.bootstrap.servers={{ .Values.app.kafka.bootstrap }}
