apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
data:
  {{- range .Values.secrets }}
  {{ .name }}: {{ .value }}
  {{- end }}